---
id: "0001"
out_path: 'output/apex/0001/'
tb_log_path: 'output/apex/0001/tblog/'

# Environment
image_size: 64
stroke_length: 300
n_step: 3
discount_factor: 0.99

# Actor
eps_base: 0.4
eps_alpha: 1
epsilon_decay: 0.995
epsilon_min: 0.03
batch_send_interval: 32
update_interval: 300

# Learner
learner_tau: 0.0005
learning_rate: 0.00005
batch_size: 64
batch_queue_size: 16
prios_queue_size: 16
param_queue_size: 3
n_recv_batch_process: 1
publish_param_interval: 50
save_param_interval: 7500

# for ReplayMemory
replay_buffer_size: 30000
replay_buffer_alpha: 0.6

# for Discriminator
pre_learning_rate: 0.00005
pre_num_epoch: 512
